name: Update Downloads URLs

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "Version (semver) for the latest release."
        default: "0.0.1"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VERSION: ${{ github.event.inputs.version }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.nvm
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: |
          npm ci

      - name: Update downloads.json
        run: |
          npm run update-downloads-urls ${{ env.VERSION }}

      - name: Commit & push
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'padloc@users.noreply.github.com'
          git commit -am "GitHub Action: Automatic update for v${{ env.VERSION }} of downloads.json"
          git push
